language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - travis_retry composer self-update
  - printf "\n" | pecl install imagick
  - travis_retry composer install --prefer-source --no-interaction;

script:
  - ./vendor/bin/phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml;

after_script:
  - ./vendor/bin/php-coveralls -v;

branches:
  only:
    - master

notifications:
    on_success: never
    on_failure: always
